events {}

http {
    log_format main '$remote_addr - $http_x_forwarded_for - [$time_local] '
                    '"$request" $status $body_bytes_sent '
                    '"$http_referer" "$http_user_agent"';

    # SCENARIO75{/opt/admin/logs}
    access_log  /opt/admin/logs/access.log main;
    error_log   /opt/admin/logs/error.log warn;

    server {
        listen 3075;

        location / {
            allow 10.10.14.0/24; # SCENARIO75{10.10.14.0/24}
            allow 192.168.1.0/24;
            deny all;
        }
    }
}
